"""
Custom Gesture Model Trainer
=============================
Trains a RandomForest classifier on landmark CSVs from collect_gesture_data.py
and exports two artefacts:

  tools/models/gesture_model.pkl   — scikit-learn model (used by Python app)
  tools/models/gesture_model.json  — portable JSON weights (used by browser / TF.js)

Usage:
    python tools/train_gesture_model.py

Requirements:
    pip install scikit-learn

To plug the model into main.py, import and call  predict_gesture(lm_list)
from src/custom_gesture_predictor.py (auto-generated next to the model).
"""

import csv
import json
import os
import sys
import pickle

import numpy as np

DATA_DIR  = os.path.join(os.path.dirname(__file__), "gesture_data")
MODEL_DIR = os.path.join(os.path.dirname(__file__), "models")
os.makedirs(MODEL_DIR, exist_ok=True)


# ── Load dataset ──────────────────────────────────────────────────────────────
def load_dataset():
    X, y = [], []
    labels = []

    if not os.path.isdir(DATA_DIR):
        sys.exit(f"[Trainer] Data directory not found: {DATA_DIR}\n"
                 "  Run collect_gesture_data.py first.")

    csv_files = [f for f in os.listdir(DATA_DIR) if f.endswith(".csv")]
    if len(csv_files) < 2:
        sys.exit("[Trainer] Need at least 2 gesture classes. "
                 "Collect more data with collect_gesture_data.py")

    for fname in csv_files:
        label = fname[:-4]
        labels.append(label)
        path = os.path.join(DATA_DIR, fname)
        with open(path) as f:
            reader = csv.reader(f)
            rows = [list(map(float, row)) for row in reader if row]
        if len(rows) < 30:
            print(f"[Trainer] Warning: only {len(rows)} samples for '{label}' — collect more.")
        for row in rows:
            X.append(row)
            y.append(label)

    return np.array(X), np.array(y), sorted(set(labels))


# ── Train ─────────────────────────────────────────────────────────────────────
def train(X, y, labels):
    try:
        from sklearn.ensemble import RandomForestClassifier
        from sklearn.model_selection import cross_val_score, train_test_split
        from sklearn.preprocessing import LabelEncoder
    except ImportError:
        sys.exit("[Trainer] scikit-learn not found. Install it:\n  pip install scikit-learn")

    le = LabelEncoder()
    y_enc = le.fit_transform(y)

    X_tr, X_te, y_tr, y_te = train_test_split(X, y_enc, test_size=0.2, random_state=42, stratify=y_enc)

    clf = RandomForestClassifier(n_estimators=200, max_depth=15, random_state=42, n_jobs=-1)
    clf.fit(X_tr, y_tr)

    acc = clf.score(X_te, y_te)
    cv  = cross_val_score(clf, X, y_enc, cv=5).mean()
    print(f"\n[Trainer] Test accuracy : {acc:.1%}")
    print(f"[Trainer] CV  accuracy  : {cv:.1%}")

    return clf, le


# ── Export model ──────────────────────────────────────────────────────────────
def export_pkl(clf, le):
    path = os.path.join(MODEL_DIR, "gesture_model.pkl")
    with open(path, "wb") as f:
        pickle.dump({"model": clf, "label_encoder": le}, f)
    print(f"[Trainer] Saved pkl  → {path}")
    return path


def export_json(clf, le):
    """Export a minimal decision-tree-forest JSON for browser use.
    Each tree's structure is serialised as nested dicts."""
    from sklearn.tree import _tree

    def tree_to_dict(tree, feature_names=None):
        t = tree.tree_
        def recurse(node):
            if t.feature[node] == _tree.TREE_UNDEFINED:
                return {"leaf": True, "value": int(np.argmax(t.value[node][0]))}
            return {
                "feature": int(t.feature[node]),
                "threshold": float(t.threshold[node]),
                "left":  recurse(t.children_left[node]),
                "right": recurse(t.children_right[node]),
            }
        return recurse(0)

    trees = [tree_to_dict(est) for est in clf.estimators_]
    data = {
        "classes": list(le.classes_),
        "n_features": int(clf.n_features_in_),
        "trees": trees,
    }

    path = os.path.join(MODEL_DIR, "gesture_model.json")
    with open(path, "w") as f:
        json.dump(data, f, separators=(",", ":"))
    size_kb = os.path.getsize(path) / 1024
    print(f"[Trainer] Saved json → {path}  ({size_kb:.1f} KB)")
    return path


# ── Generate predictor helper ─────────────────────────────────────────────────
def generate_predictor(labels):
    src_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "src")
    path = os.path.join(src_dir, "custom_gesture_predictor.py")
    code = f'''\
"""Auto-generated by tools/train_gesture_model.py — do not edit manually."""
import os, pickle
import numpy as np

_MODEL_PATH = os.path.join(os.path.dirname(__file__),
    "..", "tools", "models", "gesture_model.pkl")
_clf = None
_le  = None

def _load():
    global _clf, _le
    if _clf is None and os.path.exists(_MODEL_PATH):
        import pickle
        with open(_MODEL_PATH, "rb") as f:
            d = pickle.load(f)
        _clf, _le = d["model"], d["label_encoder"]

def normalise(lm_list):
    pts = np.array([[lm[1], lm[2], 0.0] for lm in lm_list], dtype=float)
    pts -= pts[0]
    scale = np.max(np.abs(pts)) or 1.0
    return (pts / scale).flatten()

def predict_gesture(lm_list):
    """Return (label, confidence) or (None, 0) if model not trained."""
    _load()
    if _clf is None or len(lm_list) < 21:
        return None, 0.0
    feat = normalise(lm_list).reshape(1, -1)
    proba = _clf.predict_proba(feat)[0]
    idx   = int(np.argmax(proba))
    label = _le.inverse_transform([idx])[0]
    return label, float(proba[idx])

GESTURE_LABELS = {labels!r}
'''
    with open(path, "w") as f:
        f.write(code)
    print(f"[Trainer] Generated  → {path}")


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print("[Trainer] Loading dataset…")
    X, y, labels = load_dataset()
    print(f"[Trainer] Classes    : {labels}")
    print(f"[Trainer] Samples    : {len(X)}")

    print("[Trainer] Training RandomForest…")
    clf, le = train(X, y, labels)

    export_pkl(clf, le)
    export_json(clf, le)
    generate_predictor(labels)

    print("\n[Trainer] Done! Plug custom gestures into main.py:")
    print("  from src.custom_gesture_predictor import predict_gesture")
    print("  label, conf = predict_gesture(lm_list)")


if __name__ == "__main__":
    main()
